services:
  db:
    container_name: commerce-db
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data
    networks:
      - commect-networks
  redis:
    container_name: commerce-redis
    image: redis:7.0.15-alpine
    ports:
    - '6379:6379'
    volumes:
    - redis_data:/data  
    networks:
      - commect-networks
  web:
    container_name: commerce-web
    build: .
    volumes:
      - .:/rails
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_development
      - REDIS_URL=redis://redis:6379/0
    networks:
      - commect-networks
  test:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis 
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_test
      - REDIS_URL=redis://redis:6379/0
    networks:
      - commect-networks
volumes:
    postgres13:
    redis_data:
networks:
  commect-networks: